//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cryptokeepers2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cryptokeepersdb1Entities1 : DbContext
    {
        public cryptokeepersdb1Entities1()
            : base("name=cryptokeepersdb1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alert> alerts { get; set; }
        public virtual DbSet<coin> coins { get; set; }
        public virtual DbSet<entity> entities { get; set; }
        public virtual DbSet<flag> flags { get; set; }
        public virtual DbSet<priority> priorities { get; set; }
        public virtual DbSet<tx> txes { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
