//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;

namespace cryptokeepers2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tx
    {
        [DisplayName("Wallet ID")]
        public string wallet { get; set; }
        public string txid { get; set; }
        public byte[] date { get; set; }
        public Nullable<bool> incoming { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<byte> coin { get; set; }
    }
}
